### ISSUE TITLE
Provide a clear implementation example 

### ISSUE THREAD

**Issue by padejar** [flmn/aly_oss#1]
Hello, could you provide a clear example on how to use the plugin? I looked into the /example/lib/main.dart file, but wasn't sure what do I have to pass in the InitRequest arguments.
For instance, how do you obtain an 'aes key' and 'iv' in this example? :
`var result = await _alyOss
                      .init(InitRequest(_uuid.v4(), 'https://<your server>/get-security-token', 'oss-cn-beijing.aliyuncs.com', '<your aes key>', '<your iv>'));`

**Comment by flmn** [comment]
There will be a back end API on your own server, the API will provide a JSON for client SDK use to contact aliyun OSS endpoint.

You can check documents on aliyun website: https://help.aliyun.com/document_detail/31920.html .

Result JSON form this API will looks like this:
{
"AccessKeyID" : "",
"AccessKeySecret" : "",
"RoleArn" : "",
"TokenExpireTime" : "900",
"PolicyFile": "policy/bucket_write_policy.txt"
}

The 'aes key' and 'iv' here just use AES algorithm to encrypt this result JSON. You can search "Java AES" for a lot of examples.

**Comment by minjie0128** [comment]
1. what's the https://<your server>/get-security-token mean ?  it is the alien server that plugin use this to get token ? can you give me more detail to use this url , thanks 
2. what is the iv mean?

**Comment by flmn** [comment]
1. You must replace https://<your server>/get-security-token with your server api url. Check [https://help.aliyun.com/document_detail/31920.html](https://help.aliyun.com/document_detail/31920.html) for how to implement this api.

2. iv is short for initial vector, it is a concept in AES algorithm. Check Java AES document for details.

Use this padding for AES: **AES/CBC/PKCS5Padding**

**Comment by padejar** [comment]
> There will be a back end API on your own server, the API will provide a JSON for client SDK use to contact aliyun OSS endpoint.
> 
> You can check documents on aliyun website: https://help.aliyun.com/document_detail/31920.html .
> 
> Result JSON form this API will looks like this:
> {
> "AccessKeyID" : "",
> "AccessKeySecret" : "",
> "RoleArn" : "",
> "TokenExpireTime" : "900",
> "PolicyFile": "policy/bucket_write_policy.txt"
> }
> 
> The 'aes key' and 'iv' here just use AES algorithm to encrypt this result JSON. You can search "Java AES" for a lot of examples.

Okay, so I have to encrypt the JSON result, but from which side? is it in the app or from the backend API?

**Comment by flmn** [comment]
> > There will be a back end API on your own server, the API will provide a JSON for client SDK use to contact aliyun OSS endpoint.
> > You can check documents on aliyun website: https://help.aliyun.com/document_detail/31920.html .
> > Result JSON form this API will looks like this:
> > {
> > "AccessKeyID" : "",
> > "AccessKeySecret" : "",
> > "RoleArn" : "",
> > "TokenExpireTime" : "900",
> > "PolicyFile": "policy/bucket_write_policy.txt"
> > }
> > The 'aes key' and 'iv' here just use AES algorithm to encrypt this result JSON. You can search "Java AES" for a lot of examples.
> 
> Okay, so I have to encrypt the JSON result, but from which side? is it in the app or from the backend API?

You encrypt from the server side, this plugin will decrypt in app.

You can check android/src/main/java/tech/jitao/aly_oss/AesHelper.java，I use this helper class also on server side.

**Comment by padejar** [comment]
Okay I'll try it, thank you for your responses! I think it'll be a lot more helpful if you provide the example in the "Example" app on the pub.dev plugin's page. :)

**Comment by padejar** [comment]
hi, so i've managed to encrypt the result and sent it. but what response should i sent back to the app for the plugin to decrypt it ? 

i made it currently like this, i use nodejs as a backend:
![image](https://user-images.githubusercontent.com/16450589/77042426-3923c580-69ee-11ea-9d41-a21700561f33.png)

**Comment by padejar** [comment]
Here's my implementation 
```
static Future uploadMedia(File media, activityType) async {
    final userRepository = UserRepository();
    final AlyOss alyOss = AlyOss();
    final _uuid = Uuid();
    String token = await userRepository.getToken();
    final url = 'http://' + Constant.MAIN_URL + '/teacher/get-upload-token?authToken=' + token;

    var testResult = await alyOss.init(InitRequest(_uuid.v4(), url, 'oss-ap-southeast-5.aliyuncs.com', 'aiva-oss-key', 'aiva-oss-key'));

    alyOss.upload(UploadRequest(_uuid.v4(), Constant.OSS_BUCKET_NAME, 'test/a.jpg', media.absolute.path));

    return result;
  }
```

I got an error like this
![image](https://user-images.githubusercontent.com/16450589/77053071-595c8000-6a00-11ea-8657-290cb94c824d.png)

**Comment by flmn** [comment]
> hi, so i've managed to encrypt the result and sent it. but what response should i sent back to the app for the plugin to decrypt it ?
> 
> i made it currently like this, i use nodejs as a backend:
> ![image](https://user-images.githubusercontent.com/16450589/77042426-3923c580-69ee-11ea-9d41-a21700561f33.png)

Use base64 to encode encrypt binary.

Your api response looks like hexadecimal.

**Comment by padejar** [comment]
> > hi, so i've managed to encrypt the result and sent it. but what response should i sent back to the app for the plugin to decrypt it ?
> > i made it currently like this, i use nodejs as a backend:
> > ![image](https://user-images.githubusercontent.com/16450589/77042426-3923c580-69ee-11ea-9d41-a21700561f33.png)
> 
> Use base64 to encode encrypt binary.
> 
> Your api response looks like hexadecimal.

okay, do I need to wrap it in some variable or just send it plain ?

**Comment by flmn** [comment]
@padejar  Just send it plain

**Comment by neutralino-ai** [comment]
Consider https://security.stackexchange.com/questions/178315/do-i-need-additional-encryption-on-top-of-https-for-a-rest-api , https is enough and aes encryption is not needed.
