### ISSUE TITLE
我想请教下<your iv>这个参数是哪里来的

### ISSUE THREAD

**Issue by jishaofeng89** [flmn/aly_oss#6]
var result = await _alyOss
                      .init(InitRequest(_uuid.v4(), 'https://<your server>/get-security-token', 'oss-cn-beijing.aliyuncs.com', '<your aes key>', '<your iv>'));

我想请教下<your iv>这个参数是哪里来的

**Comment by flmn** [comment]
从阿里云拿到的token信息是需要保密的，所以这里用了一下 AES 加密，在 AES 加密中，需要 IV 这个变量，翻译成初始向量，你可以搜索代码 AesHelper，服务端用的也是这个类做的加密。

**Comment by jishaofeng89** [comment]
这个iv值是自己可以随机生成的一个字符串吗

**Comment by flmn** [comment]
> 这个iv值是自己可以随机生成的一个字符串吗

是的，保持客户端跟服务端一致就行，这个串要保密。

**Comment by jishaofeng89** [comment]
服务端有参考代码吗，请教大佬

**Comment by flmn** [comment]
> 服务端有参考代码吗，请教大佬

你看看这个 #1
